openapi: 3.0.0
info:
  title: "balapi"
  contact:
    email: gkal@happyonline.gr
  version: 1.0.0
servers:
  - url: "http://127.0.0.1:8000/api"
    description: Local
  - url: "https://balaki.happyoffline.eu/api"
    description: Production
paths:
  /players:
    $ref: "./paths/players/Players.yaml"
  /players/{id}:
    $ref: "./paths/players/PlayersId.yaml"
  /teams:
    $ref: "./paths/teams/Teams.yaml"
  /teams/{id}:
    $ref: "./paths/teams/TeamsId.yaml"
  /teams/{id}/players:
    $ref: "./paths/teams/TeamsIdPlayers.yaml"
  /teams/{teamId}/players/{playerId}:
    $ref: "./paths/teams/TeamsIdPlayersId.yaml"
  /championships:
    $ref: "./paths/championships/Championships.yaml"
  /championships/{id}:
    $ref: "./paths/championships/ChampionshipsId.yaml"
  /championships/{id}/close:
    $ref: "./paths/championships/ChampionshipsIdClose.yaml"
  /games:
    $ref: "./paths/games/Games.yaml"
  /games/{id}:
    $ref: "./paths/games/GamesId.yaml"
  /results:
    $ref: "./paths/results/Results.yaml"